---
- hosts: local
  connection: local
  gather_facts: False
  vars:
    instance_type: t2.micro
    security_group: webservers_sg
    image: ami-0a63f96e85105c6d3
    keypair: mahabira
    region: us-east-2
    count: 1
  vars_files:
    - aws_keys.yml
  tasks:
    - name: Create a security group
      ec2_group:
        name: webservers_sg
        description: The webservers security group
        region: us-east-2
        aws_access_key: AKIAIZ3RUEH6FE7ASUEQ
        aws_secret_key: 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
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
    - name: Launch the new EC2 Instance
      ec2:
        aws_access_key: AKIAIZ3RUEH6FE7ASUEQ
        aws_secret_key: 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
        group: launch-wizard-1
        instance_type: t2.micro
        image: ami-0a63f96e85105c6d3
        wait: true
        region: us-east-2
        keypair: mahabira
        count: 1
      register: ec2
    - name: Add the newly created host so that we can further contact it
      add_host:
        name: "{{ item.public_ip }}"
        groups: webservers
      with_items: "{{ ec2.instances }}"
    - name: Add tag to Instance(s)
      ec2_tag:
        aws_access_key: AKIAIZ3RUEH6FE7ASUEQ
        aws_secret_key: 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
        resource: "{{ item.id }}"
        region: us-east-2
        state: "present"
      with_items: "{{ ec2.instances }}"
      args:
        tags:
          Type: webserver
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
      with_items: "{{ ec2.instances }}"
- hosts: webservers
  remote_user: ubuntu
  become: yes
  gather_facts: no
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get install python3 -y' 
   
